version: '3.3'

services:

  # minio DB 
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "test"
      MINIO_ROOT_PASSWORD: "test12345" 
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./minio/data:/data"
    command: server --console-address :9001 /data

  # Hello-world app
  hello-world-python:
    build:
      context: ./
      dockerfile: python.Dockerfile
    image: hello-world-python:v1
    restart: on-failure
    depends_on:
      - minio

